project:
  type: website
  output-dir: _site

website:
  title: "R/Pharma"
  image: "images/logo-rinpharma.png"
  favicon: "favicon.png"
  google-analytics: "G-SRBLBCD4NS"
  open-graph: true
  twitter-card: true
  site-url: https://rinpharma.com
  repo-url: https://github.com/rinpharma/rinpharma
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer:
    left: |
      Proud organizer of 
      [![](/images/logo-rinpharma.png){fig-alt="OS in Pharma logo" width=65px}](https://www.rinpharma.com)
    center:
      - text: About
        href: about.qmd
      - text: Privacy Policy
        href: privacy.qmd
      - text: Terms and Conditions
        href: terms.qmd
#      - text: "FAQ"
#        href: docs/faq/index.qmd
      - text: License
        href: license.qmd
    right:
      - icon: youtube
        href: https://www.youtube.com/rinpharma
        aria-label: R/Pharma YouTube
      - icon: linkedin
        href: https://www.linkedin.com/company/open-source-in-pharma/
        aria-label: R/Pharma LinkedIn
      - icon: twitter
        href: https://twitter.com/rinpharma
        aria-label: R/Pharma Twitter
      - icon: github
        href: https://github.com/rinpharma
        aria-label: R/Pharma github
#      - icon: rss
#        href: 
#        aria-label:      
  announcement: 
    icon: info-circle
    dismissable: true
    content: "R in Pharma is from Nov 3-7, register now! Final program and workshop is in the works!"
    type: primary
    position: below-navbar
  navbar:
    background: light
    logo: images/logo-rinpharma.png
    logo-alt: "R/Pharma logo."
    title: false
    collapse-below: lg
    left:
      - text: Overview
        href: index.qmd
      - text: Events
        href: docs/events/index.qmd
      - text: Summit
        href: docs/summit/index.qmd
      - text: People
        href: docs/people/index.qmd
      - text: Blog
        href: docs/blog/index.qmd
      - text: Support
        href: docs/support/index.qmd
    right:
      - icon: youtube
        href: https://www.youtube.com/rinpharma
        aria-label: R/Pharma YouTube
      - icon: linkedin
        href: https://www.linkedin.com/company/open-source-in-pharma/
        aria-label: R/Pharma LinkedIn
      - icon: twitter
        href: https://twitter.com/rinpharma
        aria-label: R/Pharma Twitter
      - icon: github
        href: https://github.com/openpharma
        aria-label: OpenPharma github
#      - icon: rss
#        href: 
#        aria-label:         

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html

filters:
  - filters/tools-tabset.lua


execute:
  freeze: auto

editor: visual
